// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data/process_event_payload.proto

package org.codetome.riptide.protobuf;

public interface ProcessEventPayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:data.ProcessEventPayload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>map&lt;string, string&gt; extra_data = 3;</code>
   */
  int getExtraDataCount();
  /**
   * <code>map&lt;string, string&gt; extra_data = 3;</code>
   */
  boolean containsExtraData(
      java.lang.String key);
  /**
   * Use {@link #getExtraDataMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getExtraData();
  /**
   * <code>map&lt;string, string&gt; extra_data = 3;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getExtraDataMap();
  /**
   * <code>map&lt;string, string&gt; extra_data = 3;</code>
   */

  java.lang.String getExtraDataOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; extra_data = 3;</code>
   */

  java.lang.String getExtraDataOrThrow(
      java.lang.String key);
}
